# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    debtcollection.form.registration:
        class: DebtCollectionBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: debtcollection_user_registration }
    debtcollection.user.roles:
        class: DebtCollectionBundle\Model\RoleHelper
        arguments: ['%roles%']
    debtcollection.user.form.roles:
        class: DebtCollectionBundle\Form\Type\RoleType
        arguments: ['%roles%']