# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    debtcollection.form.registration:
        class: DebtCollectionBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: debtcollection_user_registration }