#    debt_collection.example:
#        class: DebtCollectionBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
    debtcollection.form.type.role:
        class: DebtCollectionBundle\Form\Type\RoleType
        arguments:
            - '%roles%'
        tags:
            - { name: form.type }