<?php

namespace DebtCollectionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DebtCaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DebtCaseRepository extends EntityRepository
{
}
